// state.js
import { S3_BASE_URL } from "./config.js";

export const state = {
    gameData: null,
    playerEvents: {},
    chart: null,
    player: null,
    isPlaying: false,
    replayTimeouts: [],
    replayAnimationFrame: null,
    currentTime: 0,
    teamScores: {},
    teamFullTimeline: {},
    playerTimelines: {},
    selectedPlayers: new Set(),
    splitWorm: false,
    comparisonDetails: true,
    hiddenTeams: null, // null = all teams visible; otherwise Set of hidden team IDs
    selectedGame: null,
    playbackRate: 1,
    livePlaybackLocked: false,
    isGameLoading: false,
    loadingStart: 0,
    gameSignatures: {},
    games: [],
    gamesIndexLoaded: false,
    events: [],
    reloadReplenishment: {},
    latestGame: null,
    liveGameKey: null,
    liveGameData: null,
    liveSubscribed: false,
    liveSeqNo: -1,
    followLiveGames: false,
    gameFilter: "all",
    eventFilter: "none",
    gameDateFilter: "all",
    autoEventFilterDisabledFor: "",
    followedPlayers: new Map(),
    favouritesOnly: false,
    S3_BASE_URL,
};
