name: 🗂 Generate games index

on:
  push:
    # whenever you add, remove, or update JSONs in data/games
    paths:
      - 'data/games/**'

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      # 1) pull down your code
      - uses: actions/checkout@v3

      # 2) set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) run your generator script
      - name: Generate games index
        run: |
          python server_scripts/generate_games_index.py

      # 4) commit index.json back if it changed
      - name: Commit index.json
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: vinxa@github.com
          message: chore: update data/games/index.json
          add: 'data/games/index.json'
